variables:
  PROJECT_NAME: 'kudiba/area-butler'

default:
  image: docker:20.10.6
  tags:
    - hetzner

build:
  stage: build
  tags:
    - hetzner
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker tag ${PROJECT_NAME} ${PROJECT_NAME}-${CI_BUILD_REF_SLUG}:${CI_COMMIT_SHORT_SHA}

deploy-dev:
  stage: deploy
  tags:
    - hetzner
  environment:
    name: dev
    url: 'https://area-butler.dev.area-butler.de/'
    on_stop: undeploy-dev
  script:
    - cat $DEV_ENV > .env
    - apk add --no-cache docker-compose
    - docker-compose -p 'area-butler' down || true
    - docker-compose -p 'area-butler' up -d
  only:
    - main

undeploy-dev:
  stage: deploy
  tags:
    - hetzner
  variables:
    GIT_STRATEGY: none # requiring a deleted branch is not possible
  environment:
    name: dev
    action: stop
  when: manual
  script:
    - apk add --no-cache docker-compose
    - docker-compose -p 'area-butler' down || true
    - docker-compose -p 'area-butler' rm --force
    - echo "Image deleted"
  only:
    - main

deploy-prod:
  stage: deploy
  tags:
    - hetzner
  environment:
    name: production
    url: 'https://app.area-butler.de/'
    on_stop: undeploy-prod
  when: manual
  script:
    - cat $PROD_ENV > .env
    - apk add --no-cache docker-compose
    - docker-compose -p 'area-butler-prod' down || true
    - docker-compose -p 'area-butler-prod' -f docker-compose-prod.yml up -d
  only:
    - main