stages:
  - build
  - deploy

variables:
  PROD_BRANCH: "main"
  DEV_BRANCH: "dev"
  PROJECT_NAME: "kudiba/area-butler"

default:
  image: docker:26.1.4
  tags:
    - hetzner

build:
  stage: build
  script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker tag ${PROJECT_NAME} ${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}

deploy-dev:
  stage: deploy
  environment:
    name: dev
    url: "https://areabutler.dev.areabutler.de/"
  #    on_stop: undeploy-dev
  script:
    - cat $DEV_ENV > .env
    - apk add --no-cache docker-compose
    - docker-compose -p 'area-butler' down || true
    - docker-compose -p 'area-butler' up -d
  rules:
    - if: $CI_COMMIT_REF_NAME == $DEV_BRANCH # available for both commits and MRs

#undeploy-dev:
#  stage: deploy
#  variables:
#    GIT_STRATEGY: none # requiring a deleted branch is not possible
#  environment:
#    name: dev
#    action: stop
#  when: manual
#  script:
#    - apk add --no-cache docker-compose
#    - docker-compose -p 'area-butler' down || true
#    - docker-compose -p 'area-butler' rm --force
#    - echo "Image deleted"
#  rules:
#    - if: $CI_COMMIT_REF_NAME == $DEV_BRANCH # available for both commits and MRs

deploy-test:
  stage: deploy
  environment:
    name: test
    url: "https://areabutler.test.areabutler.de/"
  when: manual
  script:
    - cat $TEST_ENV > .env
    - apk add --no-cache docker-compose
    - docker-compose -p 'areabutler-test' down || true
    - docker-compose -p 'areabutler-test' -f docker-compose-test.yml up -d

deploy-prod:
  stage: deploy
  environment:
    name: production
    url: "https://app.areabutler.de/"
  script:
    - cat $PROD_ENV > .env
    - apk add --no-cache docker-compose
    - docker-compose -p 'area-butler-prod' down || true
    - docker-compose -p 'area-butler-prod' -f docker-compose-prod.yml up -d
  rules:
    - if: $CI_COMMIT_REF_NAME == $PROD_BRANCH # available for both commits and MRs
