version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "30"

services:
  area-butler-db-prod:
    image: mongo:5.0.2
    container_name: area-butler-db-prod
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - web
    expose:
      - 27017
    volumes:
      - area-butler-db-prod:/data/db
      - area-butler-db-dump-prod:/dump
    labels:
      - "traefik.enable=false"
    logging: *default-logging

  area-butler-prod:
    image: "${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}"
    container_name: area-butler-app-prod
    restart: always
    networks:
      - web
    ports:
      - 8077:3000
    volumes:
      - area-butler-assets-prod:/home/node/app/shared/assets
    environment:
      - PORT=3000
      - MAPBOX_ACCESS_TOKEN
      - MAPBOX_CREATE_TOKEN
      - AUTH0_API_DOMAIN
      - AUTH0_API_AUDIENCE
      - AUTH0_SPA_DOMAIN
      - AUTH0_SPA_AUDIENCE
      - MONGO_CONNECTION_URI
      - GOOGLE_API_KEY
      - GOOGLE_SERVER_API_KEY
      - OPENAI_API_KEY
      - PROPSTACK_CONNECT_API_KEY
      - PROPSTACK_LOGIN_SECRET
      - FEEDBACK_SLACK_WEBHOOK
      - OPERATIONS_SLACK_WEBHOOK
      - REVENUES_SLACK_WEBHOOK
      - MAIL_PROVIDER_API_KEY
      - BASE_APP_URL
      - HERE_API_KEY
      - HERE_ROUTER_API_URL
      - HERE_TRANSIT_ROUTER_API_URL
      - STRIPE_ENV
      - STRIPE_KEY
      - STRIPE_WEBHOOK_SECRET
      - STRIPE_TAX_ID
      - JWT_ROLES_CLAIM
      - OVERPASS_BASE_URL
      - OVERPASS_COUNTRIES
      - USE_OVERPASS_DB
      - ROLLBAR_ACCESS_TOKEN
      - ROLLBAR_ENVIRONMENT
      - CI_COMMIT_SHORT_SHA
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - PAYPAL_WEBHOOK_ID
      - ON_OFFICE_PROVIDER_SECRET
      - SENTRY_DSN
      - SENTRY_ENV=${CI_COMMIT_REF_SLUG}
      - REACT_APP_SENTRY_DSN
      - REACT_APP_SENTRY_ENV=${CI_COMMIT_REF_SLUG}
      - REACT_APP_BASE_URL
      - ADDR_IN_RANGE_API_TYPE
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.area-butler-prod-http.entrypoints=web"
      - "traefik.http.routers.area-butler-prod-http.middlewares=redirect"
      #      - "traefik.http.routers.area-butler-prod-http.middlewares=a-b-to-ab"
      - "traefik.http.routers.area-butler-prod-http.rule=Host(`app.area-butler.de`, `app.areabutler.de`)"
      - "traefik.http.routers.area-butler-prod.entrypoints=websecure"
      - "traefik.http.routers.area-butler-prod.rule=Host(`app.area-butler.de`, `app.areabutler.de`)"
      - "traefik.http.routers.area-butler-prod.tls=true"
      - "traefik.http.routers.area-butler-prod.tls.certresolver=le"
      - "traefik.port=8077"
    logging: *default-logging
    depends_on:
      - area-butler-db-prod

volumes:
  area-butler-db-prod:
    external: true
  area-butler-db-dump-prod:
    external: true
  area-butler-assets-prod:
    external: true

networks:
  web:
    external: true
