version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "30"

services:
  areabutler-test-db:
    image: mongo:5.0.2
    container_name: areabutler-test-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - web
    expose:
      - 27017
    volumes:
      - areabutler-test-db:/data/db
      - areabutler-test-db-dump:/dump
    labels:
      - "traefik.enable=false"
    logging: *default-logging

  areabutler-test:
    build: .
    image: kudiba/area-butler
    container_name: areabutler-test-app
    restart: always
    networks:
      - web
    ports:
      - 8072:3000
    environment:
      - PORT=3000
      - MAPBOX_ACCESS_TOKEN
      - MAPBOX_CREATE_TOKEN
      - AUTH0_API_DOMAIN
      - AUTH0_API_AUDIENCE
      - AUTH0_SPA_DOMAIN
      - AUTH0_SPA_AUDIENCE
      - MONGO_CONNECTION_URI
      - GOOGLE_API_KEY
      - GOOGLE_SERVER_API_KEY
      - OPENAI_API_KEY
      - PROPSTACK_CONNECT_API_KEY
      - PROPSTACK_LOGIN_SECRET
      - FEEDBACK_SLACK_WEBHOOK
      - OPERATIONS_SLACK_WEBHOOK
      - REVENUES_SLACK_WEBHOOK
      - MAIL_PROVIDER_API_KEY
      - BASE_APP_URL
      - HERE_API_KEY
      - HERE_ROUTER_API_URL
      - HERE_TRANSIT_ROUTER_API_URL
      - STRIPE_ENV
      - STRIPE_KEY
      - STRIPE_WEBHOOK_SECRET
      - STRIPE_TAX_ID
      - JWT_ROLES_CLAIM
      - OVERPASS_BASE_URL
      - OVERPASS_COUNTRIES
      - USE_OVERPASS_DB
      - ROLLBAR_ACCESS_TOKEN
      - ROLLBAR_ENVIRONMENT
      - CI_COMMIT_SHORT_SHA
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - PAYPAL_WEBHOOK_ID
      - ON_OFFICE_PROVIDER_SECRET
      - SENTRY_DSN
      - SENTRY_ENV
      - REACT_APP_SENTRY_DSN
      - REACT_APP_SENTRY_ENV
      - REACT_APP_BASE_URL
      - ADDR_IN_RANGE_API_TYPE
      - ON_OFFICE_IMAGES_URL
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.areabutler-test-http.entrypoints=web"
      - "traefik.http.routers.areabutler-test-http.middlewares=redirect"
      - "traefik.http.routers.areabutler-test-http.rule=Host(`areabutler.test.areabutler.de`)"
      - "traefik.http.routers.areabutler-test.entrypoints=websecure"
      - "traefik.http.routers.areabutler-test.rule=Host(`areabutler.test.areabutler.de`)"
      - "traefik.http.routers.areabutler-test.tls=true"
      - "traefik.http.routers.areabutler-test.tls.certresolver=le"
      - "traefik.port=8072"
    logging: *default-logging
    depends_on:
      - areabutler-test-db

volumes:
  areabutler-test-db:
    external: true
  areabutler-test-db-dump:
    external: true

networks:
  web:
    external: true
