version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"

x-common-env: &common-env
  OVERPASS_MODE: init
  OVERPASS_META: yes
  OVERPASS_RULES_LOAD: 10
  OVERPASS_USE_AREAS: false
  OVERPASS_MAX_TIMEOUT: 3600
  OVERPASS_SPACE: 4294967296

services:
  overpass-de:
    image: wiktorn/overpass-api
    container_name: overpass-de
    deploy:
      resources:
        limits:
          cpus: "0.2"
    restart: always
    networks:
      - web
    ports:
      - 8100:80
    volumes:
      - overpass-de-db:/db
    environment:
      <<: *common-env
      OVERPASS_PLANET_URL: http://download.geofabrik.de/europe/germany-latest.osm.bz2
      OVERPASS_DIFF_URL: http://download.openstreetmap.fr/replication/europe/germany/minute/
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overpass-de-http.entrypoints=web"
      - "traefik.http.routers.overpass-de-http.middlewares=redirect"
      - "traefik.http.routers.overpass-de-http.rule=Host(`overpass-de.areabutler.de`)"
      - "traefik.http.routers.overpass-de.entrypoints=websecure"
      - "traefik.http.routers.overpass-de.rule=Host(`overpass-de.areabutler.de`)"
      - "traefik.http.routers.overpass-de.tls=true"
      - "traefik.http.routers.overpass-de.tls.certresolver=le"
      - "traefik.port=8075"
    logging: *default-logging

  overpass-es:
    image: wiktorn/overpass-api
    container_name: overpass-es
    deploy:
      resources:
        limits:
          cpus: "0.2"
    restart: always
    networks:
      - web
    ports:
      - 8101:80
    volumes:
      - overpass-es-db:/db
    environment:
      <<: *common-env
      OVERPASS_PLANET_URL: http://download.geofabrik.de/europe/spain-latest.osm.bz2
      OVERPASS_DIFF_URL: http://download.openstreetmap.fr/replication/europe/spain/minute/
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overpass-es-http.entrypoints=web"
      - "traefik.http.routers.overpass-es-http.middlewares=redirect"
      - "traefik.http.routers.overpass-es-http.rule=Host(`overpass-es.areabutler.de`)"
      - "traefik.http.routers.overpass-es.entrypoints=websecure"
      - "traefik.http.routers.overpass-es.rule=Host(`overpass-es.areabutler.de`)"
      - "traefik.http.routers.overpass-es.tls=true"
      - "traefik.http.routers.overpass-es.tls.certresolver=le"
      - "traefik.port=8076"
    logging: *default-logging

  overpass-cy:
    image: wiktorn/overpass-api
    container_name: overpass-cy
    deploy:
      resources:
        limits:
          cpus: "0.2"
    restart: always
    networks:
      - web
    ports:
      - 8102:80
    volumes:
      - overpass-cy-db:/db
    environment:
      <<: *common-env
      OVERPASS_PLANET_URL: http://download.geofabrik.de/europe/cyprus-latest.osm.bz2
      OVERPASS_DIFF_URL: http://download.geofabrik.de/europe/cyprus-updates/
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overpass-cy-http.entrypoints=web"
      - "traefik.http.routers.overpass-cy-http.middlewares=redirect"
      - "traefik.http.routers.overpass-cy-http.rule=Host(`overpass-cy.areabutler.de`)"
      - "traefik.http.routers.overpass-cy.entrypoints=websecure"
      - "traefik.http.routers.overpass-cy.rule=Host(`overpass-cy.areabutler.de`)"
      - "traefik.http.routers.overpass-cy.tls=true"
      - "traefik.http.routers.overpass-cy.tls.certresolver=le"
      - "traefik.port=8077"
    logging: *default-logging

volumes:
  overpass-de-db:
    external: true
  overpass-es-db:
    external: true
  overpass-cy-db:
    external: true

networks:
  web:
    external: true
