version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "30"

services:
  area-butler-db:
    image: mongo:5.0.2
    container_name: area-butler-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - web
    expose:
      - 27017
    volumes:
      - area-butler-db:/data/db
      - area-butler-db-dump:/dump
    labels:
      - "traefik.enable=false"
    logging: *default-logging

  area-butler:
    build: .
    image: kudiba/area-butler
    container_name: area-butler-app
    restart: always
    networks:
      - web
    ports:
      - 8073:3000
    volumes:
      - area-butler-assets:/home/node/app/shared/assets
    #      - area-butler-ftp:/home/node/app/shared/ftp
    environment:
      - PORT=3000
      - MAPBOX_ACCESS_TOKEN
      - MAPBOX_CREATE_TOKEN
      - AUTH0_API_DOMAIN
      - AUTH0_API_AUDIENCE
      - AUTH0_SPA_DOMAIN
      - AUTH0_SPA_AUDIENCE
      - MONGO_CONNECTION_URI
      - GOOGLE_API_KEY
      - GOOGLE_SERVER_API_KEY
      - OPENAI_API_KEY
      - OPENAI_MAX_TOKENS
      - PROPSTACK_CONNECT_API_KEY
      - PROPSTACK_LOGIN_SECRET
      - FEEDBACK_SLACK_WEBHOOK
      - OPERATIONS_SLACK_WEBHOOK
      - REVENUES_SLACK_WEBHOOK
      - MAIL_PROVIDER_API_KEY
      - BASE_APP_URL
      - HERE_API_KEY
      - HERE_ROUTER_API_URL
      - HERE_TRANSIT_ROUTER_API_URL
      - STRIPE_ENV
      - STRIPE_KEY
      - STRIPE_WEBHOOK_SECRET
      - STRIPE_TAX_ID
      - JWT_ROLES_CLAIM
      - OVERPASS_BASE_URL
      - OVERPASS_COUNTRIES
      - USE_OVERPASS_DB
      - ROLLBAR_ACCESS_TOKEN
      - ROLLBAR_ENVIRONMENT
      - CI_COMMIT_SHORT_SHA
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - PAYPAL_WEBHOOK_ID
      - ON_OFFICE_PROVIDER_SECRET
      - SENTRY_DSN
      - SENTRY_ENV
      - REACT_APP_SENTRY_DSN
      - REACT_APP_SENTRY_ENV
    labels:
      - "traefik.docker.network=web"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.area-butler-http.entrypoints=web"
      - "traefik.http.routers.area-butler-http.middlewares=redirect"
      #      - "traefik.http.routers.area-butler-http.middlewares=a-b-to-ab"
      - "traefik.http.routers.area-butler-http.rule=Host(`area-butler.dev.area-butler.de`, `areabutler.dev.areabutler.de`)"
      - "traefik.http.routers.area-butler.entrypoints=websecure"
      - "traefik.http.routers.area-butler.rule=Host(`area-butler.dev.area-butler.de`, `areabutler.dev.areabutler.de`)"
      - "traefik.http.routers.area-butler.tls=true"
      - "traefik.http.routers.area-butler.tls.certresolver=le"
      - "traefik.port=8073"
    logging: *default-logging
    depends_on:
      - area-butler-db

#  area-butler-ftp:
#    image: delfer/alpine-ftp-server
#    container_name: area-butler-ftp
#    restart: always
#    networks:
#      - web
#    expose:
#      - 21
#    volumes:
#      - area-butler-ftp:/ftp/ftp
#    environment:
#      - USERS=one|1fghfsadfa3rhudhgf
#      - ADDRESS=23.88.7.41
#    labels:
#      - "traefik.enable=false"

volumes:
  area-butler-db:
    external: true
  area-butler-db-dump:
    external: true
  area-butler-assets:
    external: true
#  area-butler-ftp:
#    external: true

networks:
  web:
    external: true
