version: '3'

services:
  area-butler-db:
    image: mongo:5.0.2
    container_name: area-butler-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - web
    expose:
      - 27017
    volumes:
      - area-butler-db:/data/db
      - area-butler-db-dump:/dump
    labels:
      - 'traefik.enable=false'

  area-butler:
    build: .
    image: kudiba/area-butler
    container_name: area-butler-app
    restart: always
    networks:
      - web
    ports:
      - 8073:3000
    environment:
      - PORT=3000
      - MAPBOX_ACCESS_TOKEN
      - AUTH0_DOMAIN
      - AUTH0_AUDIENCE
      - MONGO_CONNECTION_URI
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.http.middlewares.redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.area-butler-http.entrypoints=web'
      - 'traefik.http.routers.area-butler-http.middlewares=redirect'
      - 'traefik.http.routers.area-butler-http.rule=Host(`area-butler.x.syndicats.co`)'
      - 'traefik.http.routers.area-butler.entrypoints=websecure'
      - 'traefik.http.routers.area-butler.rule=Host(`area-butler.x.syndicats.co`)'
      - 'traefik.http.routers.area-butler.tls=true'
      - 'traefik.http.routers.area-butler.tls.certresolver=le'
      - 'traefik.port=8073'

    depends_on:
      - area-butler-db

volumes:
  area-butler-db:
    external: true
  area-butler-db-dump:
    external: true

networks:
  web:
    external: true
