export enum ApiPersonaType {
    STUDENTS = 'STUDENTS',
    PROFESSIONAL_SINGLE = 'PROFESSIONAL_SINGLE',
    YOUNG_FAMILY = 'YOUNG_FAMILY',
    MIDDLE_CLASS = 'MIDDLE_CLASS',
    HIGH_CLASS = 'HIGH_CLASS',
    ACTIVE_SENIORS = 'ACTIVE_SENIORS'
}